name: "SMZDM Checkin"

on:
  push:
    # branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *'
  watch:
    types: [started]

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@master
    - 
      name: Run Env
      env:
        SMZDM_COOKIE: ${{ secrets.SMZDM_COOKIE }}
        SERVERCHAN_SECRETKEY: ${{ secrets.SERVERCHAN_SECRETKEY }}
    - 
      name: Go ENV
      uses: cedrickring/golang-action@1.6.0
      env:
        GO111MODULE: "on"
      run: go run checkin.go
